[tool.dephell.main]
from = {format = "poetry", path = "pyproject.toml"}
to = {format = "setuppy", path = "setup.py"}

[tool.poetry]
name = "beatmachine"
version = "2.2.0-alpha.1"
description = "A library for procedurally remixing songs"
authors = ["dhsavell <dhsavell05@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
pydub = "^0.23.1"
madmom = {git = "https://github.com/CPJKU/madmom.git", rev = "6e6af996dfc2473d92fa9c15f5461ede54a32384"}
deprecation = "^2.0"

[tool.poetry.dev-dependencies]
black = {version = "^18.3-alpha.0", allows-prereleases = true}
sphinx = "^2.2"
parameterized = "^0.7.1"
pre-commit = "^1.20"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
