[tool.poetry]
name = "beatmachine"
version = "3.2.0"
description = "A library for procedurally remixing songs"
authors = ["branchpanic <hi@branchpanic.me>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.10"
madmom = {git = "https://github.com/CPJKU/madmom.git", rev = "3bc8334099feb310acfce884ebdb76a28e01670d"}
soundfile = "^0.10.3"
jsonschema = "^3.2.0"
numpy = "^1.20.0"

[tool.poetry.group.dev.dependencies]
black = "^22.10.0"
sphinx = "^2.2"
parameterized = "^0.7.1"
pre-commit = "^1.20"
bump2version = "^1.0.0"
sphinx-rtd-theme = "^0.5.0"
pytest = "^7.1.3"

[tool.black]
line-length = 120

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
