[tool.poetry]
name = "beatmachine"
version = "2.2.0-dev"
description = "A library for procedurally remixing songs"
authors = ["dhsavell <dhsavell05@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
pydub = "^0.23.1"
madmom = {git = "https://github.com/CPJKU/madmom.git", rev = "6e6af99"}
deprecation = "^2.0"

[tool.poetry.dev-dependencies]
black = {version = "^18.3-alpha.0", allows-prereleases = true}
sphinx = "^2.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
