[tool.dephell.main]
from = {format = "poetry", path = "pyproject.toml"}
to = {format = "setuppy", path = "setup.py"}

[tool.poetry]
name = "beatmachine"
version = "3.2.0"
description = "A library for procedurally remixing songs"
authors = ["dhsavell <dhsavell05@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.7"
madmom = {git = "https://github.com/CPJKU/madmom.git", rev = "805c08e69b4390ce763c098474b2f96fab47bf60"}
deprecation = "^2.0"
soundfile = "^0.10.3"
schema = "^0.7.3"
jsonschema = "^3.2.0"
numpy = "^1.20.0"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
sphinx = "^2.2"
parameterized = "^0.7.1"
pre-commit = "^1.20"
pytest = "^5.3.5"
bump2version = "^1.0.0"
rope = "^0.18.0"
sphinx-rtd-theme = "^0.5.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
